baskets/urls.py
from django.urls import path

from baskets.views import basket_add, basket_remove, basket_edit, basket_remove_from_products

app_name = 'baskets'
urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket'),
    path('remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('remove_from_products/<int:product_id>/', basket_remove_from_products, name='basket_remove_from_products'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

bookshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('likes/', include('likes.urls', namespace='likes')),
    path('admins/', include('admins.urls', namespace='admins')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from likes.views import like_action, unlike

app_name = 'likes'
urlpatterns = [
    path('like_action/<int:product_id>/', like_action, name='like_action'),
    path('unlike/<int:like_id>/', unlike, name='unlike'),

]

orders/urls.py
from django.urls import path

from .views import OrderList, read, order_forming_complete, create_order, view_order

from mainapp.views import index

app_name = 'orders'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    # path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    # path('detail/', read, name='read'),
    path('view/', view_order, name='view'),
    path('create/', create_order, name='create'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
]

baskets/models.py
from django.db import models
from django.utils.functional import cached_property

from mainapp.models import Product
from users.models import User


# Create your models here.
class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    def total_sum(self):
        baskets = Basket.objects.filter(user=self.user)
        total_sum = 0
        for basket in baskets:
            if basket.product.quantity > 0:
                print(basket.product)
                total_sum += basket.sum()

        return total_sum

    def total_quantity(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.quantity for basket in baskets)

    @cached_property
    def get_items_cached(self):
        return self.user.basket.select_related()

    @staticmethod
    def get_item(pk):
        return Basket.objects.get(pk=pk).quantity

baskets/views.py
from django.contrib import messages
from django.http import JsonResponse

from django.shortcuts import HttpResponseRedirect, render
from django.template.loader import render_to_string

from mainapp.models import Product
from baskets.models import Basket

from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def basket_add(request, product_id):
    user_select = request.user
    product = Product.objects.get(id=product_id)
    Basket.objects.create(user=user_select, product=product, quantity=1)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, basket_id):
    Basket.objects.get(id=basket_id).delete()
    baskets = Basket.objects.filter(user=request.user)
    context = {
        'baskets': baskets
    }
    result = render_to_string('baskets/basket.html', context)
    return JsonResponse({'result': result})


@login_required
def basket_remove_from_products(request, product_id):
    product = Product.objects.get(id=product_id)
    print(Basket.objects.get(product=product))
    Basket.objects.get(product=product).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


@login_required()
def basket_edit(request, id, quantity):
    if is_ajax(request=request):
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            if (basket.product.quantity - basket.quantity) > 0:
                basket.quantity = quantity
                basket.save()
            # else:
            #     messages.warning(request, 'Количество данного товара ограничено на складе!')
        else:
            basket.delete()

        baskets = Basket.objects.filter(user=request.user)
        context = {
            'baskets': baskets,
        }
        result = render_to_string('baskets/basket.html', context)
        return JsonResponse({'result': result})


def basket_quantity(request):

    baskets = Basket.objects.filter(user=request.user)
    context = {
        "baskets": baskets,
    }
    return render(request, 'basket/basket_quantity.html', context)

baskets/templates/baskets/basket.html
<div class="busket_product">
    <h2 class="busket_product_heading">Корзина</h2>
    {% if baskets %}
    <div class="busket_product_list">
        {% for basket in baskets %}
        <form class="woocommerce-cart-form">
            <table class="shop_table shop_table_responsive cart woocommerce-cart-form__contents">
                <thead>
                <tr>
                    <th class="product-remove">
                        <span class="screen-reader-text">Удалить товар</span>
                    </th>
                    <th class="product-thumbnail">
                        <span class="screen-reader-text">Фото товара</span>
                    </th>
                    <th class="product-name">Товар</th>
                    <th class="product-price">Цена</th>
                    <th class="product-quantity">Количество</th>
                    <th class="product-subtotal">Подытог</th>
                </tr>

                </thead>
                <tbody>
                <tr class="woocommerce-cart-form__cart-item cart_item">
                    <td class="product-remove">
                        <a id="basket_remove" class="remove" name="{{ basket.id }}"
                           aria-label="Удалить эту позицию" data-product_id="1989"
                           data-product_sku="1500-40">
                            ×
                        </a>
                    </td>
                    <td class="product-thumbnail">
                        <a href="#">
                            <div class="product-thumbnail-img-container">
                                <img class="product-thumbnail-img"
                                     src={{basket.product.image.url}}
                                     decoding="async" fetchpriority="high">
                            </div>
                        </a>
                    </td>
                    <td class="product-name" data-title="Товар">
                        <a class="product-name-decoration" href="#">
                            {{ basket.product.name }}
                        </a>
                    </td>
                    <td class="product-price" data-title="Цена">
                            <span>
                                <bdi>
                                    {{ basket.product.price }}
                                </bdi>
                                <span>
                                    ₽
                                </span>
                            </span>
                    </td>
                    <td class="product-quantity" data-title="Количество">
                        {% if basket.product.quantity > 0 %}
                            <div class="quantity" bis_skin_checked="1">
                                <label class="screen-reader-text">Количество товара книга1</label>
                                <input id="quantity" name="{{ basket.id }}" class="input-text qty text" type="number"
                                       step="1" min="0"
                                       value="{{basket.quantity}}" title="Кол-во"
                                       size="4" placeholder inputmode="numeric" autocomplete="off">
                            </div>
                        {% else %}
                            <p>Товар распродан</p>
                        {% endif %}
                    </td>
                    <td class="product-subtotal" data-title="Подытог">
                        {% if basket.product.quantity > 0 %}
                            <span>
                                <bdi>
                                    {{ basket.sum }}
                                </bdi>
                                <span>
                                    ₽
                                </span>
                            </span>
                        {% else %}
                            <p> ---------------- </p>
                        {% endif %}

                    </td>
                </tr>
                </tbody>
            </table>
        </form>
        {% endfor %}

        <div>
            <h3 class="summ_decoration_word">Сумма заказа</h3>
            <table cellspacing="0" class="shop_table">
                <tbody>
                <tr class="order-total">
                    <th class="order-total_decoration_word">Итого</th>
                    <td class="order-total_decoration_price" data-title="Итого">
                        <strong>
                                    <span>
                                        <bdi>
                                            {{ baskets.0.total_sum }}
                                        </bdi>
                                        <span>
                                            ₽
                                        </span>
                                    </span>
                        </strong>

                    </td>
                </tr>

                </tbody>
            </table>
            <div class="button_order-container">
                <a href="{% url 'orders:view' %}" type="submit"
                   class="u-align-center-xl u-border-none u-btn u-btn-round u-button-style u-hover-palette-2-dark-2 u-palette-2-dark-1 u-radius-5 u-btn-2">
                    Оформить заказ

                </a>
            </div>
        </div>


    </div>
    {% else %}
    <div class="busket_product_list-empty">
        <h3 class="summ_decoration_word-empty">Ваша корзина пуста</h3>
        <div class="button_order-container-empty">
            <a href="/products/" type="submit"
               class="u-align-center-xl u-border-none u-btn u-btn-round u-button-style u-hover-palette-2-dark-2 u-palette-2-dark-1 u-radius-50 u-btn-2">
                Приступить к покупкам

            </a>
        </div>
    </div>
    {% endif %}
</div>