bookshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('likes/', include('likes.urls', namespace='likes')),
    path('admins/', include('admins.urls', namespace='admins')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from likes.views import like_action, unlike

app_name = 'likes'
urlpatterns = [
    path('like_action/<int:product_id>/', like_action, name='like_action'),
    path('unlike/<int:like_id>/', unlike, name='unlike'),

]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from baskets.views import basket_quantity

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:category_id>/', mainapp.products, name='category'),
    path('detail/<int:pk>/', mainapp.ProductDetail.as_view(), name='detail'),
    path('page/<int:page_id>/', mainapp.products, name='page'),

]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

import users
from users.views import LoginListView, RegisterListView, ProfileFormView, Logout, basket_order

app_name = 'users'
urlpatterns = [
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('basket_order/', basket_order, name='basket_order'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('login/', LoginListView.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),

    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify')

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category}'


class ProductImage(models.Model):
    image = models.ImageField(upload_to='product_images', blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Adds(models.Model):
    image = models.ImageField(upload_to='add_images', blank=True)

mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import DetailView
from django.views.decorators.cache import cache_page, never_cache

from django.conf import settings

from baskets.models import Basket
from likes.models import Like
from mainapp.models import Product, ProductCategory, ProductImage, Adds


def index(request):
    return render(request, 'mainapp/index.html')


@never_cache
def products(request, category_id=None, page_id=1):
    product_in_basket = []
    product_liked = []
    products = Product.objects.filter(category_id=category_id).select_related(
        'category') if category_id != None else Product.objects.all()

    paginator = Paginator(products, per_page=6)
    try:
        products_paginator = paginator.page(page_id)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    for product in Product.objects.all():
        for basket in Basket.objects.all():
            if product.id == basket.product_id:
                product_in_basket.append(product.id)
        for like in Like.objects.all():
            if product.id == like.product_id:
                product_liked.append(product.id)

    adds = Adds.objects.all()
    context = {
        "title": "BookWorld",
        "products": products_paginator,
        "categories": ProductCategory.objects.all(),
        "product_in_basket": product_in_basket,
        "product_liked": product_liked,
        "adds": adds,
    }
    context['first_add'] = context['adds'][0]
    context['len_add'] = len(context['adds'])
    if request.user.is_authenticated:
        baskets = Basket.objects.filter(user=request.user)
        context["baskets"] = baskets

    return render(request, 'mainapp/products.html', context)


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    return get_object_or_404(Product, pk=pk)


class ProductDetail(DetailView):
    model = Product
    template_name = 'mainapp/product_item.html'
    context_object_name = 'product'

    def get_context_data(self, category_id=None, *args, **kwargs):
        product_liked = []
        product_in_basket = []
        context = super().get_context_data()
        for product in Product.objects.all():
            for like in Like.objects.all():
                if product.id == like.product_id:
                    product_liked.append(product.id)
            for basket in Basket.objects.all():
                if product.id == basket.product_id:
                    product_in_basket.append(product.id)

        context['product'] = get_product(self.kwargs.get('pk'))
        context['images'] = ProductImage.objects.filter(product_id=context['product'].id)
        context['categories'] = ProductCategory.objects.all()
        context['im_len'] = len(context['images'])
        # context['first_im'] = context['images'][0]
        context['product_liked'] = product_liked
        context['product_in_basket'] = product_in_basket
        return context
# Create your views here.

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="#books24">
    <meta name="description" content="">
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>

    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i">
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">



    {% block css %}
    {% endblock %}

    {% block js %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script class="u-script" type="text/javascript" src="/static/vendor/jquery/jquery.min.js" defer=""></script>
        <script class="u-script" type="text/javascript" src="/static/vendor/jquery/jquery.js" defer=""></script>
        <script class="u-script" type="text/javascript" src="/static/js/nicepage.js" defer=""></script>
        <script type="text/javascript" src="{% static 'js/baskets.js' %}"></script>
        <script  class="u-script" src="/static/js/fixads.js" type="text/javascript"></script>
    {% endblock %}

</head>
<body data-path-to-root="./" data-include-products="false" class="u-body u-xl-mode" data-lang="ru">
    <header class="u-border-5 u-border-custom-color-4 u-clearfix u-custom-color-4 u-header u-header" id="sec-8201">
        <div class="u-clearfix u-sheet u-valign-middle-md u-valign-middle-sm u-valign-middle-xs u-sheet-1">
            <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
              <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">
                <a class="u-button-style u-custom-active-border-color u-custom-active-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-hover-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
                  <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
                  <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
                </g></svg>
                </a>
              </div>
              <div class="u-custom-menu u-nav-container">
                <ul class="u-nav u-spacing-30 u-unstyled u-nav-1 topmenu">
                    <li class="u-nav-item"><a class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" href="{% url 'index' %}" style="padding: 10px 0px;">Главная</a>
                    </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" href="{% url 'mainapp:index' %}" style="padding: 10px 0px;">Каталог</a></li>
                    {% if not user.is_authenticated %}
                        <li class="u-nav-item"><a class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" href="{% url 'users:login'%}" style="padding: 10px 0px;">Войти</a></li>
                    {% else %}
                        <li class="u-nav-item">
                            <a href="#" class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" style="padding: 10px 0px;">
                            Профиль
                            </a>
                            <ul class="submenu u-nav u-spacing-30 u-unstyled u-nav-1 u-nav-basket">
                                <li class="u-nav-item-basket">
                                    <a class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" href="{% url 'users:profile' %}" style="padding: 10px 0px;">
                                        Профиль
                                    </a>
                                </li>
                                <li class="u-nav-item-basket">
                                    <a class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" href="{% url 'users:basket_order' %}" style="padding: 10px 0px;">
                                        Корзина
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="u-nav-item"><a class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" href="{% url 'users:logout'%}" style="padding: 10px 0px;">Выйти</a></li>
                        {% if user.is_staff %}
                            <li class="u-nav-item">
                                <a class="u-border-2 u-border-active-palette-2-dark-3 u-border-hover-palette-1-dark-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-2-dark-3 u-text-hover-palette-1-dark-1 u-text-palette-2-dark-2" href="{% url 'admins:index'%}" style="padding: 10px 0px;">
                                    &#9881
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
              </div>
              <div class="u-custom-menu u-nav-container-collapse">
                <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                  <div class="u-inner-container-layout u-sidenav-overflow">
                    <div class="u-menu-close"></div>
                    <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                        <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'index' %}">Главная</a></li>
                        <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'mainapp:index' %}">Каталог</a></li>
                        {% if not user.is_authenticated %}
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'users:login'%}">Войти</a></li>
                        {% else %}
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="profile.html">Профиль</a></li>
                            <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" href="{% url 'users:basket_order' %}" style="padding: 10px 0px;">
                                        Корзина
                                    </a>
                            </li>
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'users:logout'%}">Выйти</a></li>
                            {% if user.is_staff %}
                                <li class="u-nav-item">
                                    <a class="u-border-2 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link" href="{% url 'admins:index'%}" style="padding: 10px 0px;">
                                        &#9881
                                    </a>
                                </li>
                            {% endif %}
                        {% endif %}
                    </ul>
                  </div>
                </div>
                <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
              </div>
            </nav>
        <a href="#" class="u-image u-logo u-opacity u-opacity-85 u-image-1" data-image-width="600" data-image-height="264">
          <img src="/static/vendor/img/index/Logo_2_.png" class="u-logo-image u-logo-image-1">
        </a>
      </div>
    </header>
            {% block content %}
            {% endblock %}

    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-ddb6">
        <div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">Проект выполнен: Пчеленко Е.Ю. Новичкова А.В. 4218.</p>
      </div>
        <span style="height: 74px; width: 74px; margin-left: 0px; margin-right: auto; margin-top: 0px; right: 20px; bottom: 20px;" class="u-back-to-top u-hidden-md u-icon u-opacity u-opacity-85" data-href="#">
        <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 551.13 551.13"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-1d98"></use></svg>
        <svg class="u-svg-content" enable-background="new 0 0 551.13 551.13" viewBox="0 0 551.13 551.13" xmlns="http://www.w3.org/2000/svg" id="svg-1d98"><path d="m275.565 189.451 223.897 223.897h51.668l-275.565-275.565-275.565 275.565h51.668z"></path></svg>
    </span>
    </footer>
</body>

</html>

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
        <link rel="stylesheet" href="/static/css/products.css" media="screen">
        <link rel="stylesheet" href="/static/css/page.css" media="screen">
{% endblock %}

{% block content %}
<div class="products">
  <section class="u-clearfix u-section-1" id="sec-8bb4">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="custom-expanded data-layout-selected u-clearfix u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-layout-cell u-size-17-lg u-size-17-md u-size-17-sm u-size-17-xs u-size-19-xl u-layout-cell-1">
                <div class="u-container-layout u-valign-top-lg u-valign-top-xl u-container-layout-1">
                  <h1 class="u-custom-font u-font-playfair-display u-text u-text-1">BookWorld</h1>
                  <div class="list-group">
                    {% for category in categories %}
                      <a href="{% url 'mainapp:category' category.id %}" class="list-group-item">{{category.name}}</a>
                    {% endfor %}
                  </div>
                </div>
              </div>
              <div class="u-container-style u-layout-cell u-size-41-xl u-size-43-lg u-size-43-md u-size-43-sm u-size-43-xs u-layout-cell-2">
                <div class="u-container-layout u-valign-middle-lg u-container-layout-2">
                  <div class="u-carousel u-expanded-width u-gallery u-layout-carousel u-lightbox u-no-transition u-show-text-none u-gallery-1" data-interval="5000" data-u-ride="carousel" id="carousel-3fc0">
                    <ol class="u-absolute-hcenter u-carousel-indicators u-carousel-indicators-1">
                      {% with ''|center:len_add as range %}
                      {% for _ in range %}
                        {% if forloop.counter == 0 %}
                          <li data-u-target="#carousel-3fc0" data-u-slide-to="{{ forloop.counter }}" class="u-active u-grey-70 u-shape-circle" style="width: 10px; height: 10px;"></li>
                        {% else %}
                          <li data-u-target="#carousel-3fc0" data-u-slide-to="{{ forloop.counter }}" class="u-grey-70 u-shape-circle" style="width: 10px; height: 10px;"></li>
                        {% endif %}
                      {% endfor %}
                      {% endwith %}
                    </ol>
                    <div class="u-carousel-inner u-gallery-inner" role="listbox">
                      {% for add in adds %}
                      {% if add == first_add %}
                        <div class="u-active u-carousel-item u-gallery-item u-carousel-item-1">
                          <div class="u-back-slide">
                            <img class="u-back-image u-expanded" src="{{ first_add.image.url }}">
                          </div>
                          <div class="u-over-slide u-over-slide-1"></div>
                        </div>
                      {% else %}
                        <div class="u-carousel-item u-gallery-item u-carousel-item-2">
                          <div class="u-back-slide">
                            <img class="u-back-image u-expanded" src="{{ add.image.url }}">
                          </div>
                          <div class="u-over-slide u-over-slide-2"></div>
                        </div>
                      {% endif %}
                      {% endfor %}
                    </div>
                    <a class="u-absolute-vcenter u-carousel-control u-carousel-control-prev u-grey-70 u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-white u-carousel-control-1" href="#carousel-3fc0" role="button" data-u-slide="prev">
                      <span aria-hidden="true">
                        <svg viewBox="0 0 451.847 451.847"><path d="M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0
c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744
c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z"></path></svg>
                      </span>
                      <span class="sr-only">
                        <svg viewBox="0 0 451.847 451.847"><path d="M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0
c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744
c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z"></path></svg>
                      </span>
                    </a>
                    <a class="u-absolute-vcenter u-carousel-control u-carousel-control-next u-grey-70 u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-white u-carousel-control-2" href="#carousel-3fc0" role="button" data-u-slide="next">
                      <span aria-hidden="true">
                        <svg viewBox="0 0 451.846 451.847"><path d="M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744
L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284
c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z"></path></svg>
                      </span>
                      <span class="sr-only">
                        <svg viewBox="0 0 451.846 451.847"><path d="M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744
L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284
c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z"></path></svg>
                      </span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </section>
    <section class="u-clearfix u-section-2" id="sec-f677">
          <div class="u-clearfix u-sheet u-valign-top-lg u-valign-top-md u-sheet-1">
            <div class="u-expanded-width-lg u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-list u-list-1">
              <div class="u-repeater u-repeater-1">
                  {% for product in products %}
                    <div class="u-container-style u-list-item u-repeater-item u-list-item-1 product_list_item">
                      <div class="u-container-layout u-similar-container u-container-layout-1">
                        <a href="{% url 'products:detail' product.id %}">
                          <img alt="" class="u-expanded-width-xl u-image u-image-default u-image-1" data-image-width="2000" data-image-height="1333" src={{product.image.url}} data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">
                        </a>
                        <h3 class="u-text u-text-default-lg u-text-default-md u-text-default-sm u-text-default-xl u-text-1">
                          <a href="{% url 'products:detail' product.id %}">{{product.name}} </a>
                        </h3>
                        <p class="u-text u-text-2">{{product.author.name}}</p>
                        <a class="u-active-none u-border-hover-palette-2-base u-border-none u-button-style u-hover-none u-none u-text-body-color u-btn-1"> {{product.price}} Руб</a>
                        <div class="busket_liked_container">
                          {% if product.quantity > 0 %}
                            {% if not user.is_authenticated %}
                              <a name="{{product.id}}" href="{% url 'users:login'%}" class="u-align-center-xl u-border-none u-btn u-btn-round u-button-style u-hover-palette-2-dark-2 u-palette-2-dark-1 u-radius-50 u-btn-2"> ДОБАВИТЬ В КОРЗИНУ</a>
                            {% else %}
                              {% if product.id in product_in_basket %}
                                <a name="{{product.id}}" value="{{user.is_authenticated}}" id="remove" class="u-align-center-xl u-border-none u-btn u-btn-round u-button-style u-hover-palette-2-dark-2 u-palette-2-dark-1 u-radius-50 u-btn-2"> УДАЛИТЬ ИЗ КОРЗИНЫ</a>
                              {% else %}
                                <a name="{{product.id}}" value="{{user.is_authenticated}}" id="add" class="u-align-center-xl u-border-none u-btn u-btn-round u-button-style u-hover-palette-2-dark-2 u-palette-2-dark-1 u-radius-50 u-btn-2"> ДОБАВИТЬ В КОРЗИНУ</a>
                              {% endif %}
                            {% endif %}
                          {% else %}
                            <a name="{{product.id}}" class="u-align-center-xl u-border-none u-btn-round u-button-style u-radius-50 sold-out u-btn-2"> ТОВАР РАСПРОДАН</a>
                          {% endif %}
                          <button class="button_liked_product" type="button">
                            <svg width="25" height="20" viewBox="0 -1 22 20" fill="none">
                              {% if not user.is_authenticated %}
                                <path id="{{product.id}}" onclick="location.href='{% url 'users:login'%}'" stroke="#c70000"  d="M16.749 0C13.875 0 12.676 2.75 11 2.75C9.324 2.75 8.12498 0 5.25098 0C2.52898 0 0 2.29099 0 5.38199C0 11.114 9.794 14.861 11 18C12.206 14.86 22 11.114 22 5.38199C22 2.29099 19.471 0 16.749 0Z" fill="#fff" data-spm-anchor-id="a2g2w.detail.0.i3.263872f6fDcHOp">
                                </path>
                              {% else %}
                                {% if product.id in product_liked %}
                                  <path id="{{product.id}}" type="like" stroke="#c70000" d="M16.749 0C13.875 0 12.676 2.75 11 2.75C9.324 2.75 8.12498 0 5.25098 0C2.52898 0 0 2.29099 0 5.38199C0 11.114 9.794 14.861 11 18C12.206 14.86 22 11.114 22 5.38199C22 2.29099 19.471 0 16.749 0Z" fill="#c70000" data-spm-anchor-id="a2g2w.detail.0.i3.263872f6fDcHOp">
                                  </path>
                                {% else %}
                                  <path id="{{product.id}}" type="like" stroke="#c70000" d="M16.749 0C13.875 0 12.676 2.75 11 2.75C9.324 2.75 8.12498 0 5.25098 0C2.52898 0 0 2.29099 0 5.38199C0 11.114 9.794 14.861 11 18C12.206 14.86 22 11.114 22 5.38199C22 2.29099 19.471 0 16.749 0Z" fill="#fff" data-spm-anchor-id="a2g2w.detail.0.i3.263872f6fDcHOp">
                                  </path>
                                {% endif %}
                              {% endif %}
                            </svg>
<!--                            <svg width="25" height="20" viewBox="0 -1 22 20" fill="none">-->
<!--                              <path d="M16.749 0C13.875 0 12.676 2.75 11 2.75C9.324 2.75 8.12498 0 5.25098 0C2.52898 0 0 2.29099 0 5.38199C0 11.114 9.794 14.861 11 18C12.206 14.86 22 11.114 22 5.38199C22 2.29099 19.471 0 16.749 0Z" fill="#c70000" stroke="#c70000" data-spm-anchor-id="a2g2w.detail.0.i3.263872f6fDcHOp">-->

<!--                              </path>-->
<!--                            </svg>-->

                          </button>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
              </div>
            </div>
          </div>
          <nav class="numeration_container u-clearfix u-sheet u-valign-top-lg u-valign-top-md">
                          <ul class="numeration_list">
                            {% for page in products.paginator.page_range %}
                              <li class="numeration_list_item">
                                <a class="numeration_list_item_link" href="{% url 'products:page' page %}"> {{ page }} </a>
                              </li>
                            {% endfor %}
                          </ul>
          </nav>
          {% if user.is_authenticated %}
            <div class="float-block-container">
                  <div class="float-block">
                    <a href="{% url 'users:basket_order' %}" class="busket_icon">
                      <i id="float_basket" class="fa badge fa-lg" value="{{baskets.0.total_quantity}}">&#xf290;</i>

                    </a>

                  </div>
            </div>
          {% endif %}
    </section>
</div>

{% endblock %}


</html>