bookshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('likes/', include('likes.urls', namespace='likes')),
    path('admins/', include('admins.urls', namespace='admins')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from likes.views import like_action, unlike

app_name = 'likes'
urlpatterns = [
    path('like_action/<int:product_id>/', like_action, name='like_action'),
    path('unlike/<int:like_id>/', unlike, name='unlike'),

]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

import users
from users.views import LoginListView, RegisterListView, ProfileFormView, Logout, basket_order

app_name = 'users'
urlpatterns = [
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('basket_order/', basket_order, name='basket_order'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('login/', LoginListView.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),

    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify')

]

orders/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver

from baskets.models import Basket
from mainapp.models import Product


class Order(models.Model):
    PAID = 'PD'
    PROCEEDED = 'PRD'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (PAID, 'оплачено'),
        (PROCEEDED, 'обрабатывается'),
        (CANCEL, 'отмена заказа'),

    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order_number = models.CharField(max_length=20)
    address = models.CharField(blank=True, max_length=256)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлён', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default='')
    # payment_id = models.CharField(max_length=100, null=True, blank=True)
    # payment_status = models.BooleanField(default=False)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_items(self):
        pass

    def delete(self, using=None, keep_parents=False):

        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукты', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity


@receiver(pre_delete, sender=OrderItem)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.save()


@receiver(pre_save, sender=OrderItem)
def product_quantity_update_save(sender, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - instance.get_item(int(instance.pk))
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()

users/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils.timezone import now

# Create your models here.
NULL_INSTALL = {'null': True, 'blank': True}


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{11}$',
                                 message="Номер телефона должен соответствовать формату '+79999999999' и содержать 11 знаков")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True, unique=True)
    address = models.CharField(blank=True, max_length=256)
    activation_key = models.CharField(max_length=128, **NULL_INSTALL)
    activation_key_created = models.DateTimeField(auto_now_add=True, **NULL_INSTALL)

    def is_activation_key_expired(self):
        if now() <= self.activation_key_created + timedelta(hours=48):
            return False
        return True

users/forms.py
import hashlib
import random

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'address', 'phone_number', 'image')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите адресс эл.почты'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Введите номер телефона'
        self.fields['address'].widget.attrs['placeholder'] = 'Введите свой адрес'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Подтвердите пароль'

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()
        return user


class UserProfileForm(UserChangeForm):
    class Meta:

        image = forms.ImageField(widget=forms.FileInput(), required=False)

        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'image', 'phone_number', 'address')

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.generic import UpdateView, FormView

from baskets.models import Basket
from bookshop import settings
from bookshop.mixin import BaseClassContextMixin
from likes.models import Like
from orders.models import Order
from users.forms import UserRegisterForm, UserLoginForm, UserProfileForm
from users.models import User


class RegisterListView(FormView, BaseClassContextMixin):

    model = User
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    title = 'BookWorld - Регистрация'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            if self.send_verify_link(user):
                messages.success(request, 'Подравляем! Вы успешно прошли регистрацию!')
            return redirect(self.success_url)
        # print(form.errors)
        context = {
            'form': form
        }
        return render(request, 'users/register.html', context)

    def send_verify_link(self, user):
        verify_link = reverse('users:verify', args=[user.email, user.activation_key])
        subject = f'Для активации учетной записи {user.username} пройдите по ссылке'
        message = f'Для подтверждения учетной записи {user.username} на портале \n {settings.DOMAIN_NAME}{verify_link}'
        return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)

    @staticmethod
    def verify(request, email, activation_key):
        try:
            user = User.objects.get(email=email)
            if user and user.activation_key == activation_key and not user.is_activation_key_expired():
                user.activation_key = ''
                user.activation_key_created = None
                user.is_active = True
                user.save()
                auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return render(request, 'users/verification.html')
        except Exception as e:
            print(request)
            return HttpResponseRedirect(reverse('index'))


class LoginListView(LoginView, BaseClassContextMixin):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'BookWorld - Авторизация'


class ProfileFormView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')
    title = 'BookWorld - Профиль'

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.pk)

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, request, *args, **kwargs):
        return super(ProfileFormView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProfileFormView, self).get_context_data(**kwargs)
        context['likes'] = Like.objects.filter(user=self.request.user)

        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, files=request.FILES, instance=self.get_object())
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return redirect(self.success_url)


@login_required()
def basket_order(request):
    baskets = Basket.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    context = {
        "title": "BookWorld | Корзина",
        "baskets": baskets,
        "orders": orders
    }
    return render(request, 'users/basket_order.html', context)


class Logout(LogoutView):
    template_name = 'mainapp/index.html'

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="#books24">
    <meta name="description" content="">
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>

<body>
{% block content %}
{% endblock %}
</body>

</html>

users/templates/users/basket_order.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="/static/css/profile.css" media="screen">
<link rel="stylesheet" href="/static/css/page.css" media="screen">
{% endblock %}

{% block content %}
<section class="profile">
    <div class="busket_and_liked_product">
        {% include 'baskets/basket.html' %}
        {% include 'orders/order_list.html' %}
    </div>
</section>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
      <link rel="stylesheet" href="/static/css/login.css" media="screen">
      <link rel="stylesheet" href="/static/css/page.css" media="screen">
{% endblock %}

{% block content %}
      <section class="u-align-center u-clearfix u-section-1 u-section-login">
          {% if form.errors or messages %}
                <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show"
                     role="alert"
                     style="margin-top: 50px;">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';"> &times; </span>
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    {% endif %}
                </div>
            {% endif %}
          <div class="form-container">
              <form class="form-users" action="{% url 'users:login' %}" method="post">
                  {% csrf_token %}
<!--                <form class="form-users">-->
                  <label class="visually-hidden">Имя пользователя</label>
                    {{ form.username }}
                  <label class="visually-hidden">Пароль</label>
                    {{ form.password }}
                  <a href="{% url 'users:register'%}">Ещё не зарегистрированы?</a>
                  <label class="agree"><input type="checkbox" /> Запомнить меня</label>
                  <button class="login_button">Войти</button>
              </form>
          </div>
      </section>
{% endblock %}

users/templates/users/profile.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="/static/css/profile.css" media="screen">
<link rel="stylesheet" href="/static/css/page.css" media="screen">
{% endblock %}


{% block content %}
<section class="profile">
    <div class="u-personal_data">
        <h2 class="personal_data_heading">Личные данные</h2>
        <div class="personal_data">
            <form class="personal_data" action="{% url 'users:profile' %} " method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="personal_data_container">
                    <div class="personal_data_personality">
                        <div class="personal_data_personality_card">
                            <img width="200" height="200"
                                 src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %} "
                                 class="personal_data_personality_img">
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                <p class="custom-file-label_text">Выберите изображение</p>

                            </label>
                            <h3 class="personal_data_personality_user-name">
                                {{ form.username }}
                            </h3>



                            {{ form.image }}
                        </div>

                    </div>
                </div>
                <div class="personal_data_contact-information">
                    <div class="u-personal_data_contact-information">
                        <address class="contact-inf-container">
                            <ul class="address__list">
                                <li class="address__list-item">
                                    <label for="{{ form.first_name.id_for_label }}" class="address__list-item-text">Имя:
                                        {{ form.first_name }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.last_name.id_for_label }}" class="address__list-item-text">Фамилия:
                                        {{ form.last_name }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.email.id_for_label }}" class="address__list-item-text">Email: {{ form.email }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.phone_number.id_for_label }}" class="address__list-item-text">Телефон:
                                        {{ form.phone_number }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.address.id_for_label }}" class="address__list-item-text">Адрес:
                                        {{ form.address }}</label>
                                </li>
                            </ul>

                        </address>
                    </div>

                    <div class="change_data_button">

                        <input class="u-change_data_button u-align-center-xl u-border-none u-btn u-btn-round u-button-style u-hover-palette-2-dark-2 u-palette-2-dark-1 u-btn-2"
                               type="submit" value="Сохранить">
                    </div>


                </div>
            </form>

        </div>
    </div>

    <div class="busket_and_liked_product">
        {% include 'likes/likes.html' %}


    </div>

</section>


{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
      <link rel="stylesheet" href="/static/css/register.css" media="screen">
      <link rel="stylesheet" href="/static/css/page.css" media="screen">
{% endblock %}

{% block content %}
      <section class="u-align-center u-clearfix u-section-1 u-section-login">
          <div class="form-container">
              {% if form.errors %}
                <div class="alert" role="alert" style="margin-top: 50px;">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';"> &times; </span>
                        {{ form.errors | escape }}

                </div>
              {% endif %}
                <form class="form-users" action="{% url 'users:register' %}" method="post">
                    {% csrf_token%}
                    <label for="{{ form.username.id_for_label }}" class="visually-hidden">Логин</label>
                        {{ form.username }}
                    <label for="{{ form.email.id_for_label }}" class="visually-hidden">Почта</label>
                        {{ form.email }}
                    <label for="{{ form.first_name.id_for_label }}" class="visually-hidden">Имя</label>
                        {{ form.first_name }}
                    <label for="{{ form.last_name.id_for_label }}" class="visually-hidden">Фамилия</label>
                        {{ form.last_name }}
                    <label for="{{ form.phone_number.id_for_label }}" class="visually-hidden">Номер телефона</label>
                        {{ form.phone_number }}
                    <label for="{{ form.address.id_for_label }}" class="visually-hidden">Адрес</label>
                        {{ form.address }}
                    <label for="{{ form.password1.id_for_label }}" class="visually-hidden">Пароль</label>
                        {{ form.password1 }}
                    <label for="{{ form.password2.id_for_label }}" class="visually-hidden">Повторите пароль</label>
                        {{ form.password2 }}
                    <button class="login_button">Зарегистрироваться</button>
                </form>
          </div>
      </section>
{% endblock %}

users/templates/users/verification.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="row">
        {% if user.is_authenticated %}
            <p>Почта подтверждена</p>
        {% else %}
            <p>Верификация не пройдена</p>
        {% endif %}
        <a href="{% url 'mainapp:products'%}">Перейти в магазин</a>
    </div>
{% endblock %}

users/templates/users/zakaz.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="/static/css/zakaz.css" media="screen">
<link rel="stylesheet" href="/static/css/page.css" media="screen">
{% endblock %}
        <section>
            <div>
                <div class="personal_data_contact-information">
                    <div class="u-personal_data_contact-information">
                        <address class="contact-inf-container">
                            <ul class="address__list">
                                <li class="address__list-item">
                                    <label for="{{ form.first_name.id_for_label }}" class="address__list-item-text">Имя:
                                        {{ form.first_name }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.last_name.id_for_label }}" class="address__list-item-text">Фамилия:
                                        {{ form.last_name }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.email.id_for_label }}" class="address__list-item-text">Email: {{ form.email }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.phone_number.id_for_label }}" class="address__list-item-text">Телефон:
                                        {{ form.phone_number }}</label>
                                </li>
                                <li class="address__list-item">
                                    <label for="{{ form.address.id_for_label }}" class="address__list-item-text">Адрес:
                                        {{ form.address }}</label>
                                </li>
                            </ul>

                        </address>
                    </div>
            </div>
            <div></div>
            <div></div>
        </section>

{% block content %}
{% endblock %}