admins/urls.py
from django.urls import path
from .views import (index, UserCreateView, UserUpdateView, UserDeleteView, UserListView, CategoryListView,
                    CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
                    ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, AuthorListView,
                    AuthorCreateView, AuthorUpdateView, AuthorDeleteView, AddListView, AddCreateView, AddUpdateView,
                    AddDeleteView)

app_name = 'admins'
urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admins_user'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admins_user_update'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admins_user_delete'),

    path('authors/', AuthorListView.as_view(), name='admins_author'),
    path('authors-create/', AuthorCreateView.as_view(), name='admins_author_create'),
    path('authors-update/<int:pk>/', AuthorUpdateView.as_view(), name='admins_author_update'),
    path('authors-delete/<int:pk>/', AuthorDeleteView.as_view(), name='admins_author_delete'),

    path('categories/', CategoryListView.as_view(), name='admins_category'),
    path('categories-create/', CategoryCreateView.as_view(), name='admins_category_create'),
    path('categories-update/<int:pk>/', CategoryUpdateView.as_view(), name='admins_category_update'),
    path('categories-delete/<int:pk>/', CategoryDeleteView.as_view(), name='admins_category_delete'),

    path('adds/', AddListView.as_view(), name='admins_add'),
    path('adds-create/', AddCreateView.as_view(), name='admins_add_create'),
    path('adds-update/<int:pk>/', AddUpdateView.as_view(), name='admins_add_update'),
    path('adds-delete/<int:pk>/', AddDeleteView.as_view(), name='admins_add_delete'),

    path('products/', ProductListView.as_view(), name='admins_product'),
    path('products-create/', ProductCreateView.as_view(), name='admins_product_create'),
    path('products-update/<int:pk>/', ProductUpdateView.as_view(), name='admins_product_update'),
    path('products-delete/<int:pk>/', ProductDeleteView.as_view(), name='admins_product_delete'),

]

bookshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('likes/', include('likes.urls', namespace='likes')),
    path('admins/', include('admins.urls', namespace='admins')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from likes.views import like_action, unlike

app_name = 'likes'
urlpatterns = [
    path('like_action/<int:product_id>/', like_action, name='like_action'),
    path('unlike/<int:like_id>/', unlike, name='unlike'),

]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

import users
from users.views import LoginListView, RegisterListView, ProfileFormView, Logout, basket_order

app_name = 'users'
urlpatterns = [
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('basket_order/', basket_order, name='basket_order'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('login/', LoginListView.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),

    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify')

]

admins/templates/admins/admin-adds-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Реклама</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Реклама
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Картинка рекламы</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Картинка рекламы</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for add in object_list %}
                                <tr>
                                    <td>
                                        <a href="{% url 'admins:admins_add_update' add.id %}">
                                            <img width="100" height="100"
                                                     src="{{ add.image.url }}"
                                                     class="img-thumbnail">
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_add_create' %}">
                            <button class="btn btn-success">Создать рекламу</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-adds-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование рекламы</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_add_update' add.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.image.id_for_label }}">Реклама</label>
                                    {{ form.image }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <form action="{% url 'admins:admins_add_delete' add.id %}" method="post">
                                {% csrf_token %}
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-authors-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание автора</h1>
                <form action="{% url 'admins:admins_author_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Автор</label>
                            {{ form.name }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-authors-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Авторы</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Авторы
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Автор</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Автор</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for author in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:admins_author_update' author.id %}" style="color: dodgerblue">{{ author.name }}</a></td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_author_create' %}">
                            <button class="btn btn-success">Создать автора</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-authors-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование автора | {{ author.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_author_update' author.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Автор</label>
                                    {{ form.name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <form action="{% url 'admins:admins_author_delete' author.id %}" method="post">
                                {% csrf_token %}
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-categories-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание категории</h1>
                <form action="{% url 'admins:admins_category_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Название категории</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-categories-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Категории</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Название категории</th>
                                    <th>Описание</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Название категории</th>
                                    <th>Описание</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for category in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:admins_category_update' category.id %}" style="color: dodgerblue">{{ category.name }}</a></td>
                                    <td>{{ category.description }}</td>

                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_category_create' %}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-products-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Продукты</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукты
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Название продукта</th>
                                    <th>Изображение продукта</th>
                                    <th>Автор</th>
                                    <th>Описание</th>
                                    <th>Цена продукта</th>
                                    <th>Кол-во единиц продукта</th>
                                    <th>Категория</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Название продукта</th>
                                    <th>Изображение продукта</th>
                                    <th>Автор</th>
                                    <th>Описание</th>
                                    <th>Цена продукта</th>
                                    <th>Кол-во единиц продукта</th>
                                    <th>Категория</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for product in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admins_product_update' product.id %}"
                                               style="color: dodgerblue">{{ product.name }}</a></td>
                                        <td><img width="100" height="100"
                                                 src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %} "
                                                 class="img-thumbnail"></td>
                                        <td>{{ product.author.name }}</td>
                                        <td>{{ product.description }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.category.name }}</td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_product_create' %}">
                            <button class="btn btn-success">Создать продукт</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование продукта | {{ product.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_product_update' product.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.author.id_for_label }}">Автор</label>
                                    {{ form.author }}
                                </div>
                            </div>
                            <div class="form-row mb-2">
                                <div class="col-lg-12">
                                    <div class="custom-file">
                                        {{ form.image }}
                                        <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                                        {% if form.image %}
                                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                    {{ form.description }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена продукта</label>
                                    {{ form.price }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Кол-во единиц продукта</label>
                                    {{ form.quantity }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                    {{ form.category }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-lg-12" style="margin-top: 33px;">
                                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                                </div>
                            </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <form action="{% url 'admins:admins_product_delete' product.id %}" method="post">
                                {% csrf_token %}
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; BookWorld 2023</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title | title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index'%}">BookWorld</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
<!--            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"-->
<!--                   aria-describedby="basic-addon2"/>-->
<!--            <div class="input-group-append">-->
<!--                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>-->
<!--            </div>-->
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admins_user' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_category' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_author' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-user fa-fw"></i>
                        </div>
                        Авторы
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_product' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_add' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Реклама
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>

    {% block content %}
    {% endblock %}

</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>